Created the homepage
WildCodeSchool-2024-09/LILLE-0924-PROJECT2-G2-WILD-AWAY pull request #10
Opened 2024-11-13 14:21 UTC by MTimot

2024-11-13 14:23 UTC, itisalicia approved these changes
c'est parfait

2024-11-13 15:45 UTC, fantinerudent requested changes

2024-11-13 15:45 UTC, fantinerudent commented on client/src/components/Map.tsx
> +const marker: MapInfo[] = [
vous ne pouvez pas déplacer tout ça dans un fichier à part ?

2024-11-13 15:45 UTC, fantinerudent commented on client/src/pages/Homepage/Homepage.css
> +/* .map-container {
code mort

2024-11-13 15:45 UTC, fantinerudent commented on client/src/pages/Homepage/Homepage.tsx
> +import "./Homepage.css";
espace

2024-11-13 16:23 UTC, MTimot commented on client/src/components/Map.tsx
> +const marker: MapInfo[] = [
Normalement tout est réglé !!

2024-11-13 16:23 UTC, MTimot commented on client/src/components/Map.tsx
> +const marker: MapInfo[] = [
je dois refaire une pr ?

2024-11-14 14:05 UTC, fantinerudent approved these changes
GOOD JOB

2024-11-15 09:19 UTC, merged