Us06 booking
WildCodeSchool-2024-09/LILLE-0924-PROJECT2-G2-WILD-AWAY pull request #11
Opened 2024-11-13 14:31 UTC by Arnaud6216

2024-11-13 14:34 UTC, itisalicia approved these changes
good

2024-11-13 15:46 UTC, fantinerudent requested changes

2024-11-13 15:46 UTC, fantinerudent commented on client/src/pages/booking/Booking.tsx
> +
ligne inutile

2024-11-13 16:05 UTC, Arnaud6216 commented on client/src/pages/booking/Booking.tsx
> +
C'est le titre de la page qui sera remplacé par l'appel de l'api selon le pays cliqué

2024-11-14 13:16 UTC, MTimot approved these changes

2024-11-14 13:32 UTC, fantinerudent commented on client/src/pages/booking/Booking.tsx
> +
c'était la ligne 9 inutile pas la 8 haha

2024-11-14 13:33 UTC, fantinerudent approved these changes

2024-11-14 13:54 UTC, merged